/**
 * AutobahnChargingStation automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AutobahnCoordinate} from "./AutobahnCoordinate";
export interface AutobahnChargingStation {
    id?: string
    title?: string
    description?: Array<string>
    coordinate?: AutobahnCoordinate
}
