/**
 * AutobahnChargingStationCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {AutobahnChargingStation} from "./AutobahnChargingStation";

export interface AutobahnChargingStationCollection {
    entries?: Array<AutobahnChargingStation>
}

