/**
 * AutobahnChargingStationTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {AutobahnChargingStationCollection} from "./AutobahnChargingStationCollection";
import {Response} from "./Response";
import {ResponseException} from "./ResponseException";

export class AutobahnChargingStationTag extends TagAbstract {
    /**
     * Returns available charging stations for a specific autobahn
     *
     * @returns {Promise<AutobahnChargingStationCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(autobahnId: string): Promise<AutobahnChargingStationCollection> {
        const url = this.parser.url('/autobahn/:autobahn_id/charging_station', {
            'autobahn_id': autobahnId,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as AutobahnChargingStationCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
