/**
 * AutobahnParkingLorry automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AutobahnCoordinate} from "./AutobahnCoordinate";
export interface AutobahnParkingLorry {
    id?: string
    title?: string
    subtitle?: string
    description?: Array<string>
    coordinate?: AutobahnCoordinate
    features?: Array<string>
}
