/**
 * AutobahnCoordinate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface AutobahnCoordinate {
    lat?: string
    long?: string
}
