/**
 * AutobahnClosureCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AutobahnClosure} from "./AutobahnClosure";
export interface AutobahnClosureCollection {
    entries?: Array<AutobahnClosure>
}
