/**
 * AutobahnTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {AutobahnChargingStationTag} from "./AutobahnChargingStationTag";
import {AutobahnClosureTag} from "./AutobahnClosureTag";
import {AutobahnCollection} from "./AutobahnCollection";
import {AutobahnParkingLorryTag} from "./AutobahnParkingLorryTag";
import {AutobahnWarningTag} from "./AutobahnWarningTag";
import {Response} from "./Response";
import {ResponseException} from "./ResponseException";

export class AutobahnTag extends TagAbstract {
    public chargingStation(): AutobahnChargingStationTag
    {
        return new AutobahnChargingStationTag(
            this.httpClient,
            this.parser
        );
    }

    public closure(): AutobahnClosureTag
    {
        return new AutobahnClosureTag(
            this.httpClient,
            this.parser
        );
    }

    public parkingLorry(): AutobahnParkingLorryTag
    {
        return new AutobahnParkingLorryTag(
            this.httpClient,
            this.parser
        );
    }

    public warning(): AutobahnWarningTag
    {
        return new AutobahnWarningTag(
            this.httpClient,
            this.parser
        );
    }

    /**
     * Returns all available autobahns
     *
     * @returns {Promise<AutobahnCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(): Promise<AutobahnCollection> {
        const url = this.parser.url('/autobahn', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as AutobahnCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
