/**
 * AutobahnParkingLorryCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AutobahnParkingLorry} from "./AutobahnParkingLorry";
export interface AutobahnParkingLorryCollection {
    entries?: Array<AutobahnParkingLorry>
}
