/**
 * AutobahnWarning automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AutobahnCoordinate} from "./AutobahnCoordinate";
export interface AutobahnWarning {
    id?: string
    blocked?: boolean
    future?: boolean
    title?: string
    subtitle?: string
    description?: Array<string>
    startDate?: string
    coordinate?: AutobahnCoordinate
    lineString?: Array<AutobahnCoordinate>
}
