/**
 * AutobahnWarningCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AutobahnWarning} from "./AutobahnWarning";
export interface AutobahnWarningCollection {
    entries?: Array<AutobahnWarning>
}
