/**
 * BudgetCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Budget} from "./Budget";

export interface BudgetCollection {
    entries?: Array<Budget>
}

