/**
 * BudgetIncomeTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {BudgetCollection} from "./BudgetCollection";
import {Response} from "./Response";
import {ResponseException} from "./ResponseException";

export class BudgetIncomeTag extends TagAbstract {
    /**
     * Returns income for the provided year
     *
     * @returns {Promise<BudgetCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(year: string): Promise<BudgetCollection> {
        const url = this.parser.url('/budget/income/:year', {
            'year': year,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as BudgetCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
