/**
 * Budget automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Budget {
    id?: string
    label?: string
    value?: number
    relativeToParentValue?: number
    relativeValue?: number
}

