/**
 * BudgetTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {BudgetExpenseTag} from "./BudgetExpenseTag";
import {BudgetIncomeTag} from "./BudgetIncomeTag";

export class BudgetTag extends TagAbstract {
    public expense(): BudgetExpenseTag
    {
        return new BudgetExpenseTag(
            this.httpClient,
            this.parser
        );
    }

    public income(): BudgetIncomeTag
    {
        return new BudgetIncomeTag(
            this.httpClient,
            this.parser
        );
    }


}
