/**
 * BundesratMember automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BundesratMember {
    honorificTitle?: string
    firstName?: string
    name?: string
    party?: string
    state?: string
    member?: boolean
    designated?: boolean
    url?: string
    imagePath?: string
    imageDate?: string
    detail?: string
    bio?: string
    address?: string
}
