/**
 * BundestagMember automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BundestagConstituency} from "./BundestagConstituency";
export interface BundestagMember {
    id?: string
    name?: string
    party?: string
    bioUrl?: string
    state?: string
    constituency?: BundestagConstituency
    elected?: string
    photo?: string
    photoLarge?: string
    photoLastChanged?: string
    lastChanged?: string
}
