/**
 * BundestagMemberTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {BundestagMember} from "./BundestagMember";
import {BundestagMemberCollection} from "./BundestagMemberCollection";
import {Response} from "./Response";
import {ResponseException} from "./ResponseException";

export class BundestagMemberTag extends TagAbstract {
    /**
     * Returns specific member of the Bundestag
     *
     * @returns {Promise<BundestagMember>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async get(memberId: string): Promise<BundestagMember> {
        const url = this.parser.url('/bundestag/member/:member_id', {
            'member_id': memberId,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as BundestagMember;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Returns all current members of the Bundestag
     *
     * @returns {Promise<BundestagMemberCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(): Promise<BundestagMemberCollection> {
        const url = this.parser.url('/bundestag/member', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as BundestagMemberCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
