/**
 * BundestagMemberCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BundestagMember} from "./BundestagMember";
export interface BundestagMemberCollection {
    entries?: Array<BundestagMember>
}
