/**
 * BundesratMemberTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {BundesratMemberCollection} from "./BundesratMemberCollection";
import {Response} from "./Response";
import {ResponseException} from "./ResponseException";

export class BundesratMemberTag extends TagAbstract {
    /**
     * Returns all current members of the Bundesrat
     *
     * @returns {Promise<BundesratMemberCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(): Promise<BundesratMemberCollection> {
        const url = this.parser.url('/bundesrat/member', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as BundesratMemberCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
