/**
 * BundesratMemberCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {BundesratMember} from "./BundesratMember";

export interface BundesratMemberCollection {
    entries?: Array<BundesratMember>
}

