/**
 * BundestagMemberTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {TagAbstract} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {BundestagMember} from "./BundestagMember";
import {BundestagMemberCollection} from "./BundestagMemberCollection";
import {ResponseException} from "./ResponseException";

export class BundestagMemberTag extends TagAbstract {
    /**
     * Returns specific member of the Bundestag
     *
     * @returns {Promise<BundestagMember>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async get(memberId: string): Promise<BundestagMember> {
        const url = this.parser.url('/bundestag/member/:member_id', {
            'member_id': memberId,
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            params: this.parser.query({
            }, [
            ]),
        };

        try {
            const response = await this.httpClient.request<BundestagMember>(params);
            return response.data;
        } catch (error) {
            if (error instanceof ClientException) {
                throw error;
            } else if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    case 400:
                        throw new ResponseException(error.response.data);
                    case 404:
                        throw new ResponseException(error.response.data);
                    case 500:
                        throw new ResponseException(error.response.data);
                    default:
                        throw new UnknownStatusCodeException('The server returned an unknown status code');
                }
            } else {
                throw new ClientException('An unknown error occurred: ' + String(error));
            }
        }
    }

    /**
     * Returns all current members of the Bundestag
     *
     * @returns {Promise<BundestagMemberCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(): Promise<BundestagMemberCollection> {
        const url = this.parser.url('/bundestag/member', {
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            params: this.parser.query({
            }, [
            ]),
        };

        try {
            const response = await this.httpClient.request<BundestagMemberCollection>(params);
            return response.data;
        } catch (error) {
            if (error instanceof ClientException) {
                throw error;
            } else if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    case 400:
                        throw new ResponseException(error.response.data);
                    case 404:
                        throw new ResponseException(error.response.data);
                    case 500:
                        throw new ResponseException(error.response.data);
                    default:
                        throw new UnknownStatusCodeException('The server returned an unknown status code');
                }
            } else {
                throw new ClientException('An unknown error occurred: ' + String(error));
            }
        }
    }


}
