/**
 * BundestagConstituency automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface BundestagConstituency {
    number?: string
    name?: string
}
