/**
 * CityCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {City} from "./City";

export interface CityCollection extends Collection<City> {
}

