/**
 * CityTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {TagAbstract} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {City} from "./City";
import {CityCollection} from "./CityCollection";
import {ResponseException} from "./ResponseException";

export class CityTag extends TagAbstract {
    /**
     * Returns a specific city
     *
     * @returns {Promise<City>}
     * @throws {ResponseExceptionException}
     * @throws {ClientException}
     */
    public async get(cityId: string): Promise<City> {
        const url = this.parser.url('/city/:city_id', {
            'city_id': cityId,
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            params: this.parser.query({
            }, [
            ]),
        };

        try {
            const response = await this.httpClient.request<City>(params);
            return response.data;
        } catch (error) {
            if (error instanceof ClientException) {
                throw error;
            } else if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    case 400:
                        throw new ResponseException(error.response.data);
                    case 404:
                        throw new ResponseException(error.response.data);
                    case 500:
                        throw new ResponseException(error.response.data);
                    default:
                        throw new UnknownStatusCodeException('The server returned an unknown status code');
                }
            } else {
                throw new ClientException('An unknown error occurred: ' + String(error));
            }
        }
    }

    /**
     * Returns all available cities
     *
     * @returns {Promise<CityCollection>}
     * @throws {ResponseExceptionException}
     * @throws {ClientException}
     */
    public async getAll(startIndex?: number, state?: string, district?: string, name?: string, zipCode?: string): Promise<CityCollection> {
        const url = this.parser.url('/city', {
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            params: this.parser.query({
                'startIndex': startIndex,
                'state': state,
                'district': district,
                'name': name,
                'zipCode': zipCode,
            }, [
            ]),
        };

        try {
            const response = await this.httpClient.request<CityCollection>(params);
            return response.data;
        } catch (error) {
            if (error instanceof ClientException) {
                throw error;
            } else if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    case 400:
                        throw new ResponseException(error.response.data);
                    case 404:
                        throw new ResponseException(error.response.data);
                    case 500:
                        throw new ResponseException(error.response.data);
                    default:
                        throw new UnknownStatusCodeException('The server returned an unknown status code');
                }
            } else {
                throw new ClientException('An unknown error occurred: ' + String(error));
            }
        }
    }


}
