/**
 * CityTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {City} from "./City";
import {CityCollection} from "./CityCollection";
import {Response} from "./Response";
import {ResponseException} from "./ResponseException";

export class CityTag extends TagAbstract {
    /**
     * Returns a specific city
     *
     * @returns {Promise<City>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async get(cityId: string): Promise<City> {
        const url = this.parser.url('/city/:city_id', {
            'city_id': cityId,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as City;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Returns all available cities
     *
     * @returns {Promise<CityCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(startIndex?: number, state?: string, district?: string, name?: string, zipCode?: string): Promise<CityCollection> {
        const url = this.parser.url('/city', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'startIndex': startIndex,
                'state': state,
                'district': district,
                'name': name,
                'zipCode': zipCode,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as CityCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
