/**
 * City automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface City {
    id?: number
    state?: string
    rb?: string
    district?: string
    verb?: string
    gem?: string
    name?: string
    zipCode?: string
    area?: number
}
