/**
 * CityCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {City} from "./City";
export type CityCollection = Collection<City>;
