/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ClientAbstract, CredentialsInterface, TokenStoreInterface, HttpRequest} from "sdkgen-client"
import {OAuth2} from "sdkgen-client"
import {Anonymous} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {AuthorizationTag} from "./AuthorizationTag";
import {AutobahnTag} from "./AutobahnTag";
import {BudgetTag} from "./BudgetTag";
import {BundesratTag} from "./BundesratTag";
import {BundestagTag} from "./BundestagTag";
import {CityTag} from "./CityTag";
import {DistrictTag} from "./DistrictTag";
import {HospitalTag} from "./HospitalTag";
import {JobTag} from "./JobTag";
import {MetaTag} from "./MetaTag";
import {NewsTag} from "./NewsTag";
import {StateTag} from "./StateTag";
import {WarningTag} from "./WarningTag";

export class Client extends ClientAbstract {
    public authorization(): AuthorizationTag
    {
        return new AuthorizationTag(
            this.httpClient,
            this.parser
        );
    }

    public autobahn(): AutobahnTag
    {
        return new AutobahnTag(
            this.httpClient,
            this.parser
        );
    }

    public budget(): BudgetTag
    {
        return new BudgetTag(
            this.httpClient,
            this.parser
        );
    }

    public bundesrat(): BundesratTag
    {
        return new BundesratTag(
            this.httpClient,
            this.parser
        );
    }

    public bundestag(): BundestagTag
    {
        return new BundestagTag(
            this.httpClient,
            this.parser
        );
    }

    public city(): CityTag
    {
        return new CityTag(
            this.httpClient,
            this.parser
        );
    }

    public district(): DistrictTag
    {
        return new DistrictTag(
            this.httpClient,
            this.parser
        );
    }

    public hospital(): HospitalTag
    {
        return new HospitalTag(
            this.httpClient,
            this.parser
        );
    }

    public job(): JobTag
    {
        return new JobTag(
            this.httpClient,
            this.parser
        );
    }

    public meta(): MetaTag
    {
        return new MetaTag(
            this.httpClient,
            this.parser
        );
    }

    public news(): NewsTag
    {
        return new NewsTag(
            this.httpClient,
            this.parser
        );
    }

    public state(): StateTag
    {
        return new StateTag(
            this.httpClient,
            this.parser
        );
    }

    public warning(): WarningTag
    {
        return new WarningTag(
            this.httpClient,
            this.parser
        );
    }



    public static build(clientId: string, clientSecret: string, tokenStore: TokenStoreInterface|null, scopes: Array<string>|null): Client
    {
        return new Client('https://api.deutschland-api.dev', new OAuth2(clientId, clientSecret, 'https://api.deutschland-api.dev/authorization/token', 'https://api.deutschland-api.dev/authorization/authorize', tokenStore, scopes));
    }

    public static buildAnonymous(): Client
    {
        return new Client('https://api.deutschland-api.dev', new Anonymous());
    }
}
