/**
 * DistrictTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {District} from "./District";
import {DistrictCollection} from "./DistrictCollection";
import {Response} from "./Response";
import {ResponseException} from "./ResponseException";

export class DistrictTag extends TagAbstract {
    /**
     * Returns a specific district
     *
     * @returns {Promise<District>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async get(districtId: string): Promise<District> {
        const url = this.parser.url('/district/:district_id', {
            'district_id': districtId,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as District;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Returns all available districts
     *
     * @returns {Promise<DistrictCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(startIndex?: number, state?: string, name?: string): Promise<DistrictCollection> {
        const url = this.parser.url('/district', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'startIndex': startIndex,
                'state': state,
                'name': name,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as DistrictCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
