/**
 * District automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface District {
    id?: string
    state?: string
    type?: string
    name?: string
    nuts3?: string
    area?: number
}
