/**
 * DistrictCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {District} from "./District";

export interface DistrictCollection extends Collection<District> {
}

