/**
 * HospitalCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {Hospital} from "./Hospital";

export interface HospitalCollection extends Collection<Hospital> {
}

