/**
 * HospitalCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Hospital} from "./Hospital";
export type HospitalCollection = Collection<Hospital>;
