/**
 * HospitalTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {HospitalCollection} from "./HospitalCollection";
import {Response} from "./Response";
import {ResponseException} from "./ResponseException";

export class HospitalTag extends TagAbstract {
    /**
     * Returns all available hospitals
     *
     * @returns {Promise<HospitalCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(startIndex?: number, search?: string): Promise<HospitalCollection> {
        const url = this.parser.url('/hospital', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'startIndex': startIndex,
                'search': search,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as HospitalCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
