/**
 * Job automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {JobLocation} from "./JobLocation";
export interface Job {
    job?: string
    title?: string
    number?: string
    location?: JobLocation
    employer?: string
    publishDate?: string
    entranceDate?: string
}
