/**
 * JobCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {Job} from "./Job";

export interface JobCollection extends Collection<Job> {
}

