/**
 * JobCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Job} from "./Job";
export type JobCollection = Collection<Job>;
