/**
 * JobCoordinate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface JobCoordinate {
    id?: string
    title?: string
    address?: string
    link?: string
}
