/**
 * JobLocation automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {JobCoordinate} from "./JobCoordinate";
export interface JobLocation {
    zip?: string
    place?: string
    state?: string
    country?: string
    coordinate?: JobCoordinate
}
