/**
 * JobTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {JobCollection} from "./JobCollection";
import {Response} from "./Response";
import {ResponseException} from "./ResponseException";

export class JobTag extends TagAbstract {
    /**
     * Returns all available jobs
     *
     * @returns {Promise<JobCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(page?: number, search?: string, location?: string, employer?: string): Promise<JobCollection> {
        const url = this.parser.url('/job', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'page': page,
                'search': search,
                'location': location,
                'employer': employer,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as JobCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
