/**
 * NewsTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {NewsCollection} from "./NewsCollection";
import {Response} from "./Response";
import {ResponseException} from "./ResponseException";

export class NewsTag extends TagAbstract {
    /**
     * Returns all Tagesschau news
     *
     * @returns {Promise<NewsCollection>}
     * @throws {ResponseException}
     * @throws {ClientException}
     */
    public async getAll(page?: number): Promise<NewsCollection> {
        const url = this.parser.url('/news', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'page': page,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as NewsCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 404) {
            throw new ResponseException(await response.json() as Response);
        }

        if (statusCode === 500) {
            throw new ResponseException(await response.json() as Response);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
