/**
 * NewsCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {News} from "./News";

export interface NewsCollection extends Collection<News> {
}

