/**
 * News automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface News {
    id?: string
    title?: string
    link?: string
    updated?: string
}

