/**
 * StateCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {State} from "./State";

export interface StateCollection extends Collection<State> {
}

