/**
 * StateCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {State} from "./State";
export type StateCollection = Collection<State>;
