/**
 * StateCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {State} from "./State";

export interface StateCollection extends Collection<State> {
}

