/**
 * WarningCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Warning} from "./Warning";
export interface WarningCollection {
    entries?: Array<Warning>
}
