/**
 * Warning automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Warning {
    id?: string
    severity?: string
    urgency?: string
    type?: string
    title?: string
    startDate?: string
    expiresDate?: string
}
